schema_version: 1

context:
  name: asimtools
  version: 0.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asimtools-${{ version }}.tar.gz
  sha256: 6993dc602071d22279a54789676adacbb939fa5fc5194ba2c1f3f7e9c48ebf16

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - asim-run = asimtools.scripts.asim_run:main
      - asim-execute = asimtools.scripts.asim_execute:main
      - asim-check = asimtools.scripts.asim_check:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pandas
    - pyyaml
    - pymatgen
    - ase >=3.22.1
    - colorama
    - natsort
    - mp-api

tests:
  - python:
      imports:
        - asimtools
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - asim-run --help
      - asim-execute --help
      - asim-check --help

about:
  summary: A lightweight python package for managing and running atomic simulation workflows
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/BattModels/asimtools

extra:
  recipe-maintainers:
    - jan-janssen
